export const CONSTANT = {
  CREATE_SUCCESS: 'Create successfully...',
  UPDATE_SUCCESS: 'Update successfully...',
  DELETE_SUCCESS: 'Delete successfully...',
  FOUND_SUCCESS: 'Found successfully...',
  REGISTER_SUCCESS: 'Register successfully...',
  LOGIN_SUCCESS: 'Login successfully...',
  NOT_FOUND: 'Not found',
  PLEASE_REGISTER: 'Please register',
  PLEASE_LOGIN: 'Please login',
  WRONG_CREDENTIALS: 'Wrong Credentials',
  EMAIL_ALREADY_INUSE: 'Email already in use so use different email',
  TOKEN_EMPTY: 'no token or no api key,authorization denied',
  NOT_ALLOW: 'Yor are not allowed to access this page',
};
